### ISSUE TITLE
Demo voelt beetje kapot aan zonder JS

### ISSUE THREAD

**Issue by KrijnHoetmer** [melvinr/melvinr.github.io#10]
Ik zie dingen als 'Notification permission' en 'Notify me' staan, maar ik snap de functie van je demo niet zo goed, denk ik. Result staat ook wat vaag uitgelijnd, dus het lijkt net alsof er dingen ontbreken.

Wat is de core functionaliteit van je demo?

**Comment by KoopReynders** [comment]
Wat heb je hier aan gedaan?

**Comment by melvinr** [comment]
Ik heb alle extra's uit mijn demo gestript en deze teruggebracht naar zijn core functionaliteit, namelijk updates doen van de score.

**Comment by KoopReynders** [comment]
Done
