### ISSUE TITLE
Wat doet <a href="leicester_result.html" role="button">

### ISSUE THREAD

**Issue by KrijnHoetmer** [melvinr/melvinr.github.io#11]
Wat betekent deze combinatie? En is dat wel de betekenis die je wilt hebben?

Controleer je HTML trouwens ook even via https://html5.validator.nu/, want ik zie nog een paar gekke dingen gebeuren daar.

**Comment by KoopReynders** [comment]
Wat heb je hier aan gedaan ?

**Comment by melvinr** [comment]
Deze knop is niet meer aanwezig in mijn code. Het idee achter de code was een link die ook als button fungeerde, op het moment dat er geen JS was zou deze linken naar een andere pagina, en als deze er wel was zou het een button zijn die een melding triggert.

**Comment by KoopReynders** [comment]
Als je PE denkt dan is het andersom. Je hebt een link, die gaat ergens heen. Als javascript ondersteund én geladen wordt kun je iets funky doen. 
En dus, foet javascript het niet? In de core functionaliteit kun je dan altijd nog ergens heen klikken.

**Comment by KoopReynders** [comment]
Done

**Comment by melvinr** [comment]
Ja dat is ook wat ik probeerde uit te leggen, maar ik denk dat ik het slecht heb verwoord. Zijn default functionaliteit was het linken naar een andere pagina, is er wel JS aanwezig en ondersteund, dan werd deze functionaliteit geblokkeerd en werd er iets funky mee gedaan haha.
