### ISSUE TITLE
Pas op met volgorde van je prefixes in CSS

### ISSUE THREAD

**Issue by KrijnHoetmer** [melvinr/melvinr.github.io#12]
Bijvoorbeeld bij je `box-shadow` prefixes.

Prefixes zijn overigens niet helemaal consequent doorgevoerd; automatiseer dit met Autoprefixer, of maak je er gewoon helemaal niet druk om (maar zorg wel voor fallbacks in browsers die de properties niet ondersteunen).

En volgens mij gaat er bij `display: flexr;` ook iets verkeerd.

**Comment by melvinr** [comment]
Ik heb autoprefixer geïnstalleerd en deze de prefixes laten bepalen.

**Comment by KoopReynders** [comment]
done
