### ISSUE TITLE
Feature detection in JS te minimaal

### ISSUE THREAD

**Issue by KrijnHoetmer** [melvinr/melvinr.github.io#13]
Je controleert wel of Notifications ondersteund zijn, maar er zijn meer browser APIs die je gebruikt en dus moet testen. Wat bijvoorbeeld als `addEventListener` of `classList` niet ondersteund wordt? Gebruik bijvoorbeeld het Cutting the Mustard principe om dit af te vangen.

**Comment by KoopReynders** [comment]
Wat heb je hier aan gedaan?

**Comment by melvinr** [comment]
In plaats van classList heb ik getElementById gebruikt, deze wordt door oude browsers wel ondersteund. AddEventListener heb ik in deze demo niet gebruikt, deze was niet nodig.

**Comment by KoopReynders** [comment]
Done
