### ISSUE TITLE
Demo te complex gemaakt met random results

### ISSUE THREAD

**Issue by KrijnHoetmer** [melvinr/melvinr.github.io#14]
Je haalt nu aardig wat dingen om willekeurige uitslagen te tonen, wat best zonde is, want je rent daarmee een beetje voorbij het principe van PE. Idee is om je HTML de bron te laten zijn (de core functionaliteit), en dat uit te werken met een (of meerdere) hippe API(s). Het voelt nu een beetje alsof je kost wat kost die hippe API wilde gebruiken, en het lijkt erop dat je de HTML achterwege hebt gelaten in dat proces. Probeer iets minder stuk te gaan op JS en je vooral op de HTML te richten.

**Comment by melvinr** [comment]
Aangepast en gebruik gemaakt van de methode van meerdere HTML pagina's, waar de relevante content staat.

**Comment by KoopReynders** [comment]
done
