### ISSUE TITLE
Feedback RTW 

### ISSUE THREAD

**Issue by Thomas-Machielsen** [melvinr/melvinr.github.io#15]
Leuk concept, het enige wat ik zou missen is de mogelijkheid om te filteren. Als ik bijvoorbeeld tomaten en komkommer in huis heb zou ik die 2 willen filteren dat daar recepten bij worden gezocht. 

Verder je thuis feed ik vraag me af of nieuwste recepten wel zo tof zijn, bij zo'n healthy food app is dan gezondste, of meeste eiwit, of meeste koolhydraten dan niet interessanter?

Mvg,
Thomas

**Comment by melvinr** [comment]
Bedankt voor je feedback! Ik zal dit meenemen in het verder uitdenken van mijn concept.
