### ISSUE TITLE
Waar is de onderkant

### ISSUE THREAD

**Issue by vasilisvg** [melvinr/melvinr.github.io#5]
Ik kan de onderkant van de layover niet vinden
http://ndoe.nl/screen/screenshot-1455290910.png

**Comment by vasilisvg** [comment]
En door position:fixed kan ik er niet bij. De layover staat ook niet in het verticaal in het midden

**Comment by melvinr** [comment]
De layover is nu verticaal gecentreerd en valt niet meer buiten beeld.
