### ISSUE TITLE
Min-content

### ISSUE THREAD

**Issue by vasilisvg** [melvinr/melvinr.github.io#6]
Waarom staat deze regel er? En wat gebeurt er als ik deze regel weghaal. 
https://github.com/melvinr/melvinr.github.io/blob/master/CSS%20To%20The%20Rescue/Week-2/css/style.css#L316

**Comment by melvinr** [comment]
De min-content regel geeft de breedte mee van het grootste element binnen de box. Ik heb extra tekst toegevoegd aan de HTML om een voorbeeld te geven van wat er kan gebeuren als je deze weghaalt.

Omdat ik geen vaste breedte aan de figcaption heb meegegeven pakt de box nu de breedte van het element dat dit wel heeft, namelijk de afbeelding. Haal je de regel weg dan schaalt de box mee met de tekst. Haal je de regel niet weg, en geef je de figcaption een grotere width dan de afbeelding, dan schaalt de box mee met de figcaption.
