### ISSUE TITLE
Link naar werkende demo ontbreekt

### ISSUE THREAD

**Issue by KrijnHoetmer** [melvinr/melvinr.github.io#9]
We missen nog een linkje in je readme! :)

**Comment by melvinr** [comment]
Ik heb hem er aan toegevoegd!

**Comment by KrijnHoetmer** [comment]
Volgens mij is die stuk..

**Comment by melvinr** [comment]
wat is er stuk?

**Comment by KoopReynders** [comment]
404

**Comment by melvinr** [comment]
Dit is de link die je moet hebben: http://melvinr.github.io/Browser%20Technologies/Week%203-versie%202/index.html

Bij mij werkt hij prima.

**Comment by KoopReynders** [comment]
Niet in je Readme

**Comment by melvinr** [comment]
Het is de readme van Week 3-Versie 2. Dit is de link naar die repo: https://github.com/melvinr/melvinr.github.io/tree/master/Browser%20Technologies/Week%203-versie%202
